name = "hugo-swortain"
license = "Creative Commons Attribution 4.0 International"
licenselink = "https://creativecommons.org/licenses/by/4.0/"
description = "An elegant open source and mobile first theme"
homepage = "https://github.com/SenjinDarashiva/hugo-uno"
tags = ["Responsive", "Awesome fonts", "Chart.js", "Lightbox", "gallery"]
features = ["blog", ]

[author]
    name = "swortain"
    homepage = "http://swortain.wang"

[original]
    author =  "swortain"
    homepage = "http://swortain.wang/"
    repo = "https://github.com/swortain/site"
